// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCstYpUIFXDNlWJiqoK31PJes3GSeOvOmE',
    appId: '1:170571433575:web:eebf5e519fa0bb42c5b6c2',
    messagingSenderId: '170571433575',
    projectId: 'rumo-f009f',
    authDomain: 'rumo-f009f.firebaseapp.com',
    storageBucket: 'rumo-f009f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxrzUn4kkUnrMeLiwxm7zIRKvk4LmrSOw',
    appId: '1:170571433575:android:1d82549e0af5da13c5b6c2',
    messagingSenderId: '170571433575',
    projectId: 'rumo-f009f',
    storageBucket: 'rumo-f009f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXtYHY_Kx3tS_LfnYFjrWMmHbyrSLnIZ0',
    appId: '1:170571433575:ios:7addd9b6fdae1c3cc5b6c2',
    messagingSenderId: '170571433575',
    projectId: 'rumo-f009f',
    storageBucket: 'rumo-f009f.firebasestorage.app',
    iosBundleId: 'com.example.rumo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXtYHY_Kx3tS_LfnYFjrWMmHbyrSLnIZ0',
    appId: '1:170571433575:ios:7addd9b6fdae1c3cc5b6c2',
    messagingSenderId: '170571433575',
    projectId: 'rumo-f009f',
    storageBucket: 'rumo-f009f.firebasestorage.app',
    iosBundleId: 'com.example.rumo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCstYpUIFXDNlWJiqoK31PJes3GSeOvOmE',
    appId: '1:170571433575:web:775b652e7482abb7c5b6c2',
    messagingSenderId: '170571433575',
    projectId: 'rumo-f009f',
    authDomain: 'rumo-f009f.firebaseapp.com',
    storageBucket: 'rumo-f009f.firebasestorage.app',
  );
}
